name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        id: build-image
        run: |
          IMAGE_URI=${{ secrets.DOCKER_HUB_USERNAME }}/testing_cicd:${{ github.sha }}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
        env:
          IMAGE_TAG: ${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name my-eks-cluster

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/my-deployment testing-cicd-9vb25=${{ secrets.DOCKER_HUB_USERNAME }}/testing_cicd:${{ github.sha }}

      - name: Scale up
        run: |
          kubectl scale deployment/my-deployment --replicas=6

      - name: Scale node
        run: |
          aws eks update-nodegroup-config --cluster-name my-eks-cluster --nodegroup-name my-node-group --scaling-config minSize=0,maxSize=5,desiredSize=0