name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        id: build-image
        run: |
          IMAGE_URI=${{ secrets.DOCKER_HUB_USERNAME }}/testing_cicd:${{ github.sha }}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
        env:
          IMAGE_TAG: ${{ github.sha }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name my-eks-cluster
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/my-deployment my-container=${{ secrets.DOCKER_HUB_USERNAME }}/testing_cicd:${{ github.sha }}